"""empty message

Revision ID: 4988e7d4a5b8
Revises: 8e33aed79a99
Create Date: 2019-05-11 18:29:03.771267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4988e7d4a5b8'
down_revision = '8e33aed79a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_tags', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_tags', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_column('post_tags', 'tag_id')
    # ### end Alembic commands ###
